# Generated by Django 4.2.5 on 2023-09-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanapi', '0003_loanapplication_last_emi_payment_date_payment_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='emi',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emis', to='loanapi.loanapplication'),
        ),
    ]
