# Generated by Django 4.2.5 on 2023-09-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapi', '0004_emi_amount_due_alter_emi_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
