# Generated by Django 4.2.5 on 2023-10-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapi', '0006_emi_amount_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
